name: Code Linting

on:
  pull_request:
    branches:
      - main
      - dev_init
  push:
    branches:
      - main
      - dev_init

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install pre-commit black isort

      - name: Run pre-commit checks
        run: pre-commit run
