name: Test Toy Model

# When to run the workflow: on push (commit) or pull request to the main branch.
on:
  push:
    branches:
      - main
      - dev_init
  pull_request:
    branches:
      - main
      - dev_init

jobs:
  build:
    runs-on: ubuntu-latest  # The environment to run tests (Ubuntu in this case).

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your code so it can be tested.

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code
        run: python train_model.py --TOY -e 5