name: Python Unit Tests

# When to run the workflow: on push (commit) or pull request to the main branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest  # The environment to run tests (Ubuntu in this case).

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your code so it can be tested.

      - name: Set up Python
        uses: actions/setup-python@v3  # Sets up Python environment.
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest